# Generated by Django 5.1.1 on 2024-09-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitanicPassengers',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('survived', models.BooleanField()),
                ('pclass', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sibsp', models.IntegerField(blank=True, null=True)),
                ('parch', models.IntegerField(blank=True, null=True)),
                ('ticket', models.CharField(blank=True, max_length=50)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cabin', models.CharField(blank=True, max_length=20)),
                ('embarked', models.CharField(blank=True, choices=[('C', 'Cherbourg'), ('S', 'Southampton'), ('Q', 'Queenstown')], max_length=1)),
            ],
        ),
    ]
