# Generated by Django 5.1.1 on 2024-09-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicpassengers',
            name='passenger_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
