# Generated by Django 5.1.1 on 2024-09-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0002_alter_titanicpassengers_passenger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicpassengers',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='titanicpassengers',
            name='pclass',
            field=models.IntegerField(choices=[(1, 'First Class'), (2, 'Second Class'), (3, 'Third Class')]),
        ),
        migrations.AlterField(
            model_name='titanicpassengers',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='titanicpassengers',
            name='survived',
            field=models.IntegerField(choices=[(0, 'Drown'), (1, 'Survived')]),
        ),
    ]
