# Generated by Django 5.1.1 on 2024-09-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0003_alter_titanicpassengers_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitanicPassenger',
            fields=[
                ('passenger_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('survived', models.IntegerField(choices=[(0, 'Drowned'), (1, 'Survived')])),
                ('pclass', models.IntegerField(choices=[(1, 'First Class'), (2, 'Second Class'), (3, 'Third Class')])),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sibsp', models.IntegerField(blank=True, null=True)),
                ('parch', models.IntegerField(blank=True, null=True)),
                ('ticket', models.CharField(blank=True, max_length=50)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cabin', models.CharField(blank=True, max_length=20)),
                ('embarked', models.CharField(blank=True, choices=[('C', 'Cherbourg'), ('S', 'Southampton'), ('Q', 'Queenstown')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='TitanicPassengers',
        ),
    ]
