# Generated by Django 5.1.1 on 2024-09-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0004_titanicpassenger_delete_titanicpassengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicpassenger',
            name='cabin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
