# Generated by Django 5.1.1 on 2024-09-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0005_alter_titanicpassenger_cabin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicpassenger',
            name='embarked',
            field=models.CharField(blank=True, choices=[('C', 'Cherbourg'), ('S', 'Southampton'), ('Q', 'Queenstown')], max_length=1, null=True),
        ),
    ]
